- Week_01/id_58/LeetCode_21_058.java
- Week_01/id_58/LeetCode_24_058.java
- Week_01/id_58/LeetCode_83_058.java
- Week_01/id_58/TestClass.java
> 20190415 58 maguangjun week01

- Week_01/id_91/LeetCode_242_091.java
- Week_01/id_91/LeetCode_441_091.java
> 091-籍东文-第一次作业

- Week_01/id_33/LeetCode_242_33.py
- Week_01/id_33/LeetCode_905_33.py
This algorithm used two integer pointer.  The i  is from the head pointer of array and the j is the end pointer of it. They moved against.
> sort array by parity 

- Week_01/id_101/LeetCode_141_101.java
- Week_01/id_101/LeetCode_142_101.java
- Week_01/id_101/LeetCode_206_101.java
- Week_01/id_101/LeetCode_20_101.java
- Week_01/id_101/LeetCode_24_101.java
- Week_01/id_101/LeetCode_25_101.java
- Week_01/id_101/NOTE.md
Homework for week 1, student number 101
> Homework for week 1, student number 101

- Week_01/id_137/LeetCode_441_137.py
- Week_01/id_137/LeetCode_687_137.py
> merge week1 task

- Week_01/id_140/Leetcode_687_140.java
- Week_01/id_140/Leetcode_905_140.java
> 第一周操作作业，学号140

- Week_01/id_2/LeetCode_242_2.cs
- Week_01/id_2/LeetCode_687_2.cs
- Week_02/id_2/LeetCode_671_2.cs
- Week_02/id_2/LeetCode_783_2.cs
> 002_第一周作业第二次提交

- Week_01/id_142/LeetCode_20_142.java
- Week_01/id_142/LeetCode_21_142.java
- Week_01/id_142/LeetCode_83_142.java
- Week_01/id_142/LeetCode_905_142.java
> not a perfect start

- Week_01/id_86/LeetCode_083_086.c
- Week_01/id_86/LeetCode_083_086.cs
- Week_01/id_86/LeetCode_083_086.py
- Week_01/id_86/LeetCode_905_086.c
- Week_01/id_86/LeetCode_905_086.cs
- Week_01/id_86/LeetCode_905_086.py
- Week_01/id_86/LeetCode_922_086.c
- Week_01/id_86/LeetCode_922_086.cs
- Week_01/id_86/LeetCode_922_086.py
- Week_02/id_86/LeetCode_242_086.c
- Week_02/id_86/LeetCode_242_086.cs
- Week_02/id_86/LeetCode_242_086.py
- Week_02/id_86/LeetCode_671_086.cs
> # 086 week1 week2

- Week_02/id_53/LeetCode_242_53.java
- Week_02/id_53/LeetCode_671_53.java
> 053_week2_作业提交

- Week_02/id_33/LeetCode_236_33.py
- Week_02/id_33/LeetCode_783_33.py
这周工作事情比较多，赶着写了两个简单的题提交。希望下周多花些时间做题。
> lastCommonAncestor  and  minDiffInBST

- Week_02/id_102/leetcode_236_102.cpp
- Week_02/id_102/leetcode_671_102.cpp
- Week_02/id_102/leetcode_783_102.cpp
week 2: Add leetcode 236, 671 and 783 by speng975
> 102(苏鹏)第二周作业

- Week_02/id_137/LeetCode_242_137.c
- Week_02/id_137/LeetCode_671_137.py
- Week_02/id_137/LeetCode_692_137.c
> hashtable and binary tree

- Week_02/id_64/LeetCode_938_64.js
> 【064-week2】作业（JavaScript）- 追加第四道题目

- Week_02/id_117/LeetCode_236_117.go
- Week_02/id_117/LeetCode_236_117_test.go
- Week_02/id_117/LeetCode_609_117.go
- Week_02/id_117/LeetCode_609_117_test.go
- Week_02/id_117/LeetCode_671_117.go
- Week_02/id_117/LeetCode_671_117_test.go
- Week_02/id_117/LeetCode_783_117.go
- Week_02/id_117/LeetCode_783_117_test.go
- Week_02/id_117/LeetCode_863_117.go
- Week_02/id_117/LeetCode_863_117_test.go
- Week_02/id_117/LeetCode_938_117.go
- Week_02/id_117/LeetCode_938_117_test.go
> the homework of week02

- Week_02/id_67/LeetCode_242_67.java
- Week_02/id_67/LeetCode_671_67.java
- Week_02/id_67/LeetCode_783_67.java
学号: 067 UserName:yulongz
第一周作业链接：https://github.com/yulongz/algorithm/tree/master/Week_02/id_67
学习感言 #376
语言: Java
> week02 simple solution

- Week_01/id_108/LeetCode_153_108.java
- Week_02/id_108/LeetCode_242_108.java
- Week_02/id_108/LeetCode_609_108.java
- Week_02/id_108/LeetCode_692_108.java
> BJ001-1904108-week02作业

- Week_02/id_136/LeetCode_242_136.js
- Week_02/id_136/LeetCode_671_136.js
https://leetcode-cn.com/problems/valid-anagram/ [js](https://github.com/yuzewang/algorithm/blob/master/Week_02/id_136/LeetCode_242_136.js)
https://leetcode-cn.com/problems/second-minimum-node-in-a-binary-tree/comments/ [js](https://github.com/yuzewang/algorithm/blob/master/Week_02/id_136/LeetCode_671_136.js)
>  #136 Week2 作业提交

- Week_02/id_140/Leetcode_671_140.java
- Week_02/id_140/Leetcode_783_140.java
> 第二周操作作业，学号140

- Week_02/id_46/leetcode_236_046.cpp
- Week_02/id_46/leetcode_671_046.cpp
- Week_02/id_46/leetcode_692_046.cpp
- Week_02/id_46/leetcode_783_046.cpp
- Week_02/id_46/leetcode_938_046.cpp
> week2作业-学号046

- Week_02/id_88/Leetcode_236_088.cpp
- Week_02/id_88/Leetcode_242_088.cpp
- Week_02/id_88/Leetcode_671_088.cpp
- Week_02/id_88/Leetcode_783_088.cpp
- Week_02/id_88/Leetcode_938_088.cpp
> 【学号：088  姓名：何伟敏】提交第二周作业

- Week_02/id_142/LeetCode_242_142.java
- Week_02/id_142/LeetCode_671_142.java
- Week_02/id_142/LeetCode_692_142.java
> week2 first commit

- Week_02/id_57/leetcode_242_057.cpp
- Week_02/id_57/leetcode_671_057.cpp
> 057 wangfan week2

- Leetcode_262_115_java.java
- Leetcode_609_115_java.java
- Leetcode_692_115_java.java
- Week_02/id_115/Leetcode_153_115_java.java
- Week_02/id_115/Leetcode_262_115_java.java
- Week_02/id_115/Leetcode_609_115_java.java
- Week_02/id_115/Leetcode_692_115_java.java
总结：关于数据映射，字符串统计或者字符串匹配，优先考虑用散列，对数据字符串处理最大，最小连续的，可以用栈来处理。
> [115-week2]

- Week_02/id_49/LeetCode_609_49.java
- Week_02/id_49/LeetCode_671_49.java
- Week_02/id_49/NOTE.md
> 049_week02_homework

- Week_01/id_129/.gitignore
- Week_01/id_129/Console.java
- Week_01/id_129/LeetCode_142_129.java
- Week_01/id_129/LeetCode_153_129.java
- Week_01/id_129/LeetCode_20_129.java
- Week_01/id_129/LeetCode_503_129.java
- Week_01/id_129/LeetCode_687_129.java
- Week_01/id_129/LeetCode_81_129.java
- Week_01/id_129/ListNode.java
- Week_01/id_129/TreeNode.java
- Week_02/id_129/LeetCode_236_129.java
- Week_02/id_129/LeetCode_242_129.java
- Week_02/id_129/LeetCode_609_129.java
- Week_02/id_129/LeetCode_671_129.java
- Week_02/id_129/LeetCode_692_129.java
- Week_02/id_129/TreeNode.java
> week2 - 129

- Week_03/id_33/LeetCode_104_33.py
- Week_03/id_33/LeetCode_997_33.py
这次选择的是一道递归求解树的高度和寻找法官的问题。问题相对来说比较简单，也挺容易想到。就寻找法官的问题来说，从题目所给的三个条件（1.小镇的法官不相信任何人。2. 每个人（除了小镇法官外）都信任小镇的法官。3. 只有一个人同时满足属性 1 和属性 2 。）很容易想到要使用两个计数器，一个记录信任别人的数目，一个记录被别人信任的数目。遍历一次trust数组，设置相应的计数器的值。再遍历两个计数器数组，根据满足第三个条件得到谁是法官。根据递归 求解树的深度相对就更加容易一点。递归地遍历左右子树，如果左右子树都为空则子树的高度为0，否则，树的高度为其左右子树中的较大者加上1。
> findJudge and maxDepth tree

- Week_03/id_53/LeetCode_703_053.java
- Week_03/id_53/LeetCode_997_053.java
> LeetCode_703_053 & LeetCode_997_053

- Week_03/id_113/leetcode_104_113.java
- Week_03/id_113/leetcode_373_113.java
No. 104
https://leetcode-cn.com/problems/maximum-depth-of-binary-tree/
No. 373
https://leetcode-cn.com/problems/find-k-pairs-with-smallest-sums/
> week3 assignment (id: 113)

- Week_03/id_102/leetcode_104_102.cpp
- Week_03/id_102/leetcode_429_102.cpp
- Week_03/id_102/leetcode_703_102.cpp
- Week_03/id_102/leetcode_997_102.cpp
> 102 week3 homework

- Week_03/id_122/LeetCode_104_122.php
- Week_03/id_122/LeetCode_200_122.php
> week-3 122

- Week_03/id_136/LeetCode_104_136.js
- Week_03/id_136/LeetCode_429_136.js
https://leetcode-cn.com/problems/maximum-depth-of-binary-tree/ [js](https://github.com/yuzewang/algorithm/blob/master/Week_03/id_136/LeetCode_104_136.js)
https://leetcode-cn.com/problems/n-ary-tree-level-order-traversal/ [js](https://github.com/yuzewang/algorithm/blob/master/Week_03/id_136/LeetCode_429_136.js)
> #136 Week3 作业提交

- Week_03/id_142/LeetCode_429_142.java
- Week_03/id_142/LeetCode_997_142.java
> week3 first commit

- Week_03/id_115/Leetcode_104_115.java
- Week_03/id_115/Leetcode_373_115.java
- Week_03/id_115/Leetcode_703_115.java
> [115-week03]

- Week_01/id_121/LeetCode_141_121.java
- Week_01/id_121/LeetCode_24_121.java
- Week_04/id_121/LeetCode_455_121.java
- Week_04/id_121/LeetCode_720_121.java
- Week_04/id_121/LeetCode_720_121_2.java
学号:121
username:lovingcodesk
第四周作业
> 121_week04_苏珂

- Week_04/id_142/LeetCode_455_142.java
- Week_04/id_142/LeetCode_714_142.java
> week4 first commit

- Week_04/id_87/LeetCode_211_87.java
- Week_04/id_87/LeetCode_241_87.java
solution for problem 211 and 241.
> 087 week 4 homework.

- Week_04/id_78/LeetCode_455_78.cpp
- Week_04/id_78/LeetCode_746_78.cpp
LeetCode_455_78.cpp
LeetCode_746_78.cpp
> 【078-week4】作业提交

- Week_04/id_6/LeetCode_241_6.java
- Week_04/id_6/LeetCode_455_6.java
- Week_04/id_6/LeetCode_720_6.java
- Week_04/id_6/LeetCode_746_6.java
- Week_04/id_6/LeetCode_784_6.java
> Week04_006

- Week_04/id_33/LeetCode_169_33.py
- Week_04/id_33/LeetCode_746_33.py
还是选着两个比较简单的算法题做了，其他难度高的感觉有些难啃，要花一些事情去想。找众数这个题用到一个哈希表记录数字出现的次数。遍历整个列表一次记录次数，再遍历哈希表找出众数。求爬楼梯花费最小的这个题目使用到动态规划的知识。
> mincostClimbingStairs and majorityElement

- Week_04/id_115/leetcode_309_115.java
- Week_04/id_115/leetcode_746_115.java
> [115-weeko4]
